services:
  - type: web
    name: dashboard-estacao
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:server
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_TABLE
        value: leituras
      - key: SUPABASE_ROW_LIMIT
        value: "100"